name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:    
    runs-on: ubuntu-20.04    
    steps:      
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3        
        with:          
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install frontend dependencies
        run: npm run frontend:install
      - name: Install backend dependencies
        run: npm run backend:install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test Backend
        run: npm run test:backend
      - name: Test Frontend
        run: npm run test:frontend
      - name: Render Deploy Action
        if: ${{ github.event_name == 'push' && !contains(toJson(join(github.event.commits.*.message)), '#skip') }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-cgjb18fdvk4lfi7ls8a0
          api-key: rnd_ULY6hWR0bhKM4newg2JM9iLfvIL3
      - name: Discord Webhook Notify
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with: 
          # Discord webhook URL. Should be stored in a secret and inserted as a context expression.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Severity level - info, warn, or error
          severity: info
          # Text to be sent as normal text above the embed. Use context expressions and environment variables to provide information.
          text: Version successfully deployed
      - name: Discord Webhook Notify
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          # Discord webhook URL. Should be stored in a secret and inserted as a context expression.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Severity level - info, warn, or error
          severity: error
          # Text to be sent as normal text above the embed. Use context expressions and environment variables to provide information.
          text: Deployment failed
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(toJson(join(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          DEFAULT_BUMP: patch
